logpath=.

reset=true
status=WARN
threshold=NULL
handleQtMessages=true
watchThisFile=false

appender.console.type=Console
appender.console.target=STDOUT_TARGET
appender.console.threshold=ALL
appender.console.layout.type=TTCCLayout
appender.console.layout.dateFormat=dd.MM.yyyy hh:mm:ss.zzz
appender.console.layout.contextPrinting=true

appender.daily.type=DailyFile
appender.daily.file=${logpath}/propertyconfigurator.log
appender.daily.appendFile=true
appender.daily.datePattern=_yyyy_MM_dd
appender.daily.keepDays=90
appender.daily.layout.type=TTCCLayout
appender.daily.layout.dateFormat=dd.MM.yyyy hh:mm:ss.zzz
appender.daily.layout.contextPrinting=true

rootLogger.level=ALL
rootLogger.appenderRef.console.ref=console
rootLogger.appenderRef.daily.ref=daily

logger.LoggerObjectPrio.name=LoggerObjectPrio
logger.LoggerObjectPrio.level=ERROR
logger.LoggerObjectPrio.additivity=false
logger.LoggerObjectPrio.appenderRef.daily.ref=daily
logger.LoggerObjectPrio.appenderRef.console.ref=console
